version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
      - REDIS=redis
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
